version: 31
jobs:
- name: Push to Github
  steps:
  - !PushRepository
    name: push
    remoteUrl: https://github.com/MrLinkDev/Lithium
    passwordSecret: access-token
    force: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
